# Done to increase the memory available to gradle.
org.gradle.jvmargs      = -Xmx3G
org.gradle.parallel     = true
org.gradle.warning.mode = all

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft.version = 26.2
loader.version    = 0.19.3
loom.version      = 1.17.1
java.version      = 25

# Mod Properties
mod.version = 0.1.0
mod.group   = org.voximir
mod.id      = hud-utils

# Dependencies
fabric-api.version   = 0.155.2+26.2
modmenu.version      = 20.0.1
yacl.version         = 3.9.5+26.2-fabric

loader.version.range    = >=0.18.4
minecraft.version.range = ~26.2
java.version.range      = >=25
yacl.version.range      = >=3.8.4
